# Generated by Django 6.0.4 on 2026-04-28 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='especialidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('artesano', models.ForeignKey(limit_choices_to={'tipo': 'artesano'}, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.IntegerField(choices=[(0, '0% — Excluido'), (5, '5%'), (19, '19%')], default=0)),
                ('descuento', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('artesano', models.ForeignKey(limit_choices_to={'tipo': 'artesano'}, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='usuarios.usuario')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='usuarios.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('nota', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='usuarios.producto')),
            ],
        ),
    ]
