# Generated by Django 6.0.4 on 2026-04-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_producto_codigo_barra_producto_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='valor_descuento',
            field=models.PositiveIntegerField(default=0, verbose_name='Descuento (%)'),
        ),
    ]
